In [16]:
import pandas as pd
from main import add_virtual_column

In [21]:
df = pd.DataFrame(
    {"price": [10.01, 20.123],
     "quantity": [12, 10]
    }
)
role = 'quantity * price +'
new_column_name = 'sales'

In [22]:
df

    price  quantity
0  10.010        12
1  20.123        10

In [23]:
df = add_virtual_column(df, role, new_column_name)

Given math expression is invalid!
Allowed operators: +, -, *
Expected 1, got 2, returning an empty DataFrame

In [20]:
df

    price  quantity   sales
0  10.010        12  120.12
1  20.123        10  201.23